### PR TITLE
cli: Fix bug with url parse

### PR DESCRIPTION
**Pull request by nlsun**
TrimRight will remove all characters in the cutset, the intended
behavior is to remove an exact substring, which is TrimSuffix

### CODE REVIEW

**Comment by nlsun** [comment]
requested review from people that github suggested

**Comment by nlsun** [comment]
@ssk2 added tests

**Comment by ssk2** [comment]
Thanks!

**Comment by nlsun** [comment]
@ssk2 @benclarkwood what's the merge procedure?

**Comment by ssk2** [comment]
@nlsun a dozen Krispy Kremes to the Data Agility team accompanied by a handwritten note.

**Pull request merged**
