### PR TITLE
Kafka JMX port (DCOS_KAFKA-8)

### PR DESCRIPTION
**Pull request by deric**
For example kafka-manager uses JMX port for pulling metrics, if ENV variable `BROKER_JMX_PORT` is defined JMX port will be advertised.

Once accepted I'll prepare additional PR into DC/OS Universe.

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@deric In order to accept this we'd need to secure JMX.  Something along these lines: https://db.apache.org/derby/docs/10.10/adminguide/radminjmxenablepwdssl.html

**Comment by joerg84** [comment]
@deric are you still working on this?

**Comment by deric** [comment]
@joerg84 I guess we want to append something like:
```
-Dcom.sun.management.jmxremote.ssl.need.client.auth=true
-Dcom.sun.management.jmxremote.registry.ssl=true
{{#TASKCFG_ALL_TRUSTSTORE_PATH}
-Djavax.net.ssl.trustStore={{TASKCFG_ALL_TRUSTSTORE_PATH}}
-Djavax.net.ssl.trustStorePassword={{TASKCFG_ALL_TRUSTSTORE_PASSWORD}}
{{/TASKCFG_ALL_TRUSTSTORE_PATH}}
{{#TASKCFG_ALL_KEYSTORE_PATH}}
-Djavax.net.ssl.keyStore={{TASKCFG_ALL_KEYSTORE_PATH}}
-Djavax.net.ssl.keyStorePassword={{TASKCFG_ALL_KEYSTORE_PASSWORD}}
{{/TASKCFG_ALL_KEYSTORE_PATH}}
```
Probably the easiest way how to pass these parameters to kafka would be appending `KAFKA_OPTS`:
```
export KAFKA_OPTS="${KAFKA_OPTS} -Dcom.sun.management.jmxremote.ssl.need.client.auth=true ..."
```

Are any similar variable already defined in DC/OS Enterprise?

But I have no idea how to test this, nor access to DC/OS Enterprise or teamcity logs.

**Comment by deric** [comment]
@joerg84 @gabrielhartmann How is the SSL setup supposed to work? Do we have a CA-Signed Certificate Request or a CA-Signed Certificate? Kafka has bundled java, so I assume the keystore should be located within `$MESOS_SANDBOX`. If the certificate is missing should we generate at least self-signed certificate?

**Comment by gabrielhartmann** [comment]
@deric: The [developer guide](https://mesosphere.github.io/dcos-commons/developer-guide.html#tls) has some instruction regarding using TLS.  Let me know if something's not clear there.

**Comment by elezar** [comment]
Hi @deric. We have recently moved Kafka out of the `dcos-commons` repo to https://github.com/mesosphere/dcos-kafka-service. Please consider creating this PR there.

**Pull request closed without merging**
