### PR TITLE
[INFINITY-1524] Drop prototype & spark frameworks as not used.

### PR DESCRIPTION
**Pull request by jsrodman**

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@jsrodman `settings.gradle` changes missing.  This'll fail to build I hope.

**Comment by jsrodman** [comment]
Out of morbid curiosity, I'm letting that build continue to see if it fails as desired, but e3ad1b5 i think handles it.

**Comment by jsrodman** [comment]
retest this please

**Comment by jsrodman** [comment]
Failed because of the jenkins restart.

**Pull request merged**
