### PR TITLE
Improve the handling of the ccm cluster extension

### PR DESCRIPTION
**Pull request by elezar**
Looking at the output of TC jobs like: https://teamcity.mesosphere.io/viewLog.html?buildId=732563&buildTypeId=DcosIo_DcosCommons_Hdfs_BuildAndTestPr&tab=buildLog&_focus=931

There are sometimes errors like:
```
[00:53:36]	[Step 4/4] Cluster is ready!
[00:53:36]	[Step 4/4] + true
[00:53:36]	[Step 4/4] + /build/tools/./ccm_extend.py
[00:54:07]	[Step 4/4] Looking up cluster id.
[00:54:07]	[Step 4/4] Traceback (most recent call last):
[00:54:07]	[Step 4/4] File "/build/tools/./ccm_extend.py", line 28, in <module>
[00:54:07]	[Step 4/4] all_clusters = json.loads(requests.get(base_url+'/api/cluster/active/all', headers=headers).text)
[00:54:07]	[Step 4/4] File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
[00:54:07]	[Step 4/4] return _default_decoder.decode(s)
[00:54:07]	[Step 4/4] File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
[00:54:07]	[Step 4/4] obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[00:54:07]	[Step 4/4] File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
[00:54:07]	[Step 4/4] raise JSONDecodeError("Expecting value", s, err.value) from None
[00:54:07]	[Step 4/4] json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[00:54:07]	[Step 4/4] ++ cleanup
[00:54:07]	[Step 4/4] ++ dcos-launch delete
[00:54:09]	[Step 4/4] [2017-08-08 22:54:09,085|dcos_launch.platforms.aws|INFO]: Starting bucket s3.Bucket(name='dcos-ci-test-infinity-oittve7jf-exhibitors3bucket-1nfsytqdopxdh') deletion
[00:54:09]	[Step 4/4] [2017-08-08 22:54:09,626|dcos_launch.platforms.aws|INFO]: Trying deleting bucket s3.Bucket(name='dcos-ci-test-infinity-oittve7jf-exhibitors3bucket-1nfsytqdopxdh') itself
[00:54:10]	[Step 4/4] [2017-08-08 22:54:10,165|dcos_launch.platforms.aws|INFO]: Deleting stack: arn:aws:cloudformation:us-west-2:273854932432:stack/dcos-ci-test-infinity-oittve7jfj/ff13aca0-7c8a-11e7-8d96-50a68a0e328e
[00:54:10]	[Step 4/4] [2017-08-08 22:54:10,655|dcos_launch.platforms.aws|INFO]: Delete successfully initiated for arn:aws:cloudformation:us-west-2:273854932432:stack/dcos-ci-test-infinity-oittve7jfj/ff13aca0-7c8a-11e7-8d96-50a68a0e328e
[00:54:10]	[Step 4/4] Process exited with code 1
```
meaning that even though the cluster creation is successful, we are not able to obtain the cluster id.

This PR restructures `ccm_extend.py` a little to allow for a more robust handling of the extension of the cluster.

### CODE REVIEW

**Comment by mellenburg** [comment]
@elezar CCM is notorious for doing this :/ The good news is that I've begun moving this team to a new AWS account. That is, an AWS account without CCM oppressing it :D

**Comment by elezar** [comment]
@mellenburg I see that you have removed the CCM extend step from the TC jobs. Does that mean that this PR can be closed? @pires/@dmmcquay I would recommend that you integrate these changes into your copy of this script too. The additional logging is pretty useful.

**Comment by pires** [comment]
Indeed @elezar. That's why I pinged @dmmcquay.

**Comment by mellenburg** [comment]
@elezar yes, this can now be removed as this code is no longer in use

**Comment by elezar** [comment]
Closing this PR. Will create a follow-up that removes ccm_extend.

**Comment by pires** [comment]
@elezar @mellenburg so we can safely remove `ccm_extend` script and trust TC jobs to keep clusters around for longer periods?

**Comment by dmmcquay** [comment]
@pires only if we moved to a special account that isn't connected to ccm. I don't think that includes us.

**Pull request closed without merging**
