### PR TITLE
Update version from 5.1.2 -> 5.2.1

### PR DESCRIPTION
**Pull request by loren**

### CODE REVIEW

**Comment by loren** [comment]
retest this please

**Comment by loren** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@loren: How does this work, without changing resource URIs as well?

**Comment by loren** [comment]
Not sure what you mean. The URIs are based on this ELASTIC_VERSION env var, like this:

https://github.com/loren/dcos-commons/blob/5bcd89016569c8e3189b60413b1af5e51edf0d3a/frameworks/elastic/src/main/dist/elastic_service.yml#L53-L53

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by loren** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Pull request closed without merging**
