### PR TITLE
[INFINITY-1675] kill testing virtualenvs

### PR DESCRIPTION
**Pull request by jsrodman**
Just dropping virtualenv as a prelude to actually being able to change python scripts without random unpredictable and non-reproducible breakage.

Some pain with this rollout is expected, unfortunately.

### CODE REVIEW

**Comment by benclarkwood** [comment]
@jsrodman Define expected pain?

Just unknowable breakages can be expected?

**Comment by jsrodman** [comment]
retest this please

**Comment by jsrodman** [comment]
retest this please

**Comment by jsrodman** [comment]
Oh look, it's frameworks.cassandra.tests.test_recovery.test_node_replace_replaces_node again! What a surprise!

**Comment by nickbp** [comment]
Got a rewrite of that coming in #1107, fwiw

**Pull request merged**
