### PR TITLE
[TESTS][INFINITY-1108] Added more validation in the upgrade test

### PR DESCRIPTION
**Pull request by susanxhuynh**
Added the following to the upgrade test:
- Check that the deployment finishes => this catches a failure in Elastic upgrades where the deployment never finishes.
- Check that all tasks have restarted => this catches an issue with Hello-world upgrades where the tasks are not restarted.

Elastic and hello-world upgrade tests will fail with this change.

### CODE REVIEW

**Comment by susanxhuynh** [comment]
Verified that elastic and helloworld upgrade tests have failed as expected due to these changes. Now I will disable those tests; they can be re-enabled once the upgrade issues are fixed.

**Comment by susanxhuynh** [comment]
retest this please

**Comment by susanxhuynh** [comment]
retest this please

**Comment by mbdcos** [comment]
It a custom update but please take a look at https://github.com/mesosphere/dcos-commons/blob/master/frameworks/kafka/tests/test_shakedown_upgrade.py

**Comment by mbdcos** [comment]
@susanxhuynh please see my comments above. As long as it works,LGTM.

**Comment by mbdcos** [comment]
Also it is a good idea to have:
    - update from Universe to Universe
    - update from test_version to test_version

A no change test for example in Kafka  L112 https://github.com/mesosphere/dcos-commons/blob/292e39bd9d704c9487ca49370712ce232d117cbd/frameworks/kafka/tests/test_shakedown_strategy.py

**Pull request merged**
