### PR TITLE
[SDK] Annotate Secrets tests for dcos 1.10

### PR DESCRIPTION
**Pull request by mbdcos**
SDK supports Secrets only for DC/OS 1.10

### CODE REVIEW

**Comment by jsrodman** [comment]
This seems to be how these annotations are intended to be used as the shakedown docs indicate, but I've not used them myself yet.

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
from shakedown import *

**Comment by mbdcos** [comment]
retest this please

**Pull request merged**
