### PR TITLE
[INFINITY-2223] determine upgradesFrom and downgradesTo automatically

### PR DESCRIPTION
**Pull request by elezar**
This PR backports the ability to determine `upgradesFrom` and `downgradesTo` for packages at build time. This should greatly simplify the release process in future.

I followed the following steps:
- Sync `master:/tools` with `0.30.X:/tools`. This means that #1616 is superseded.
- Copy `builds.sh` from `master`.
- Copy `sdk/bootstrap/build.sh` from `master`
- For each framework:
  - Copy `frameworks/<framework>/build.sh` from `master` and remove the `beta-references`
  - Add `upgradesTo` and `downgradesFrom` templates to `package.json`
  - Replace `dcos-<framework>` with `dcos-service-cli` in `resource.json`

I built each framework locally to generate the `upgradesFrom` and `downgradesTo` for the universe PRs.

I could have hunted through the master history to find the individual commits to cherry-pick, but thought that this would be simpler. I am open to suggestions though.

@nickbp @paegun given the recent changes to the go-vendoring, are the any reasons that the changes described here could cause issues?

@benclarkwood do we rely on any special properties of the `0.30.X` branch to get the CI builds to work?

### CODE REVIEW

**Comment by nickbp** [comment]
Not sure what the deal is with `template` but LGTM otherwise

**Comment by benclarkwood** [comment]
@elezar No, we do not rely on anything special about the branch (other than its name)

I'm not sure what is up with template. That is very odd.

**Comment by nickbp** [comment]
`template` somehow still had an old version of build.sh. Should be fixed now.

**Comment by elezar** [comment]
Thanks @nickbp. Yes, I forgot to update template.

**Pull request merged**
