### PR TITLE
[INFINITY-1448] Vendorise CLIs dependency on dcos-commons/cli

### PR DESCRIPTION
**Pull request by ssk2**
This allows us to make changes of the master branch of dcos-commons/cli without breaking the frameworks CLIs that are contained within this monorepo. 

I have tested that these each build correctly from a clean start and that the builds use the correct (i.e. vendored) dependency.

### CODE REVIEW

**Comment by benclarkwood** [comment]
@ssk2 ```dcos package install --yes cassandra
https://infinity-artifacts.s3.amazonaws.com/autodelete7d/cassandra/20170503-232409-BwRDjqGuDRBbjT9k/stub-universe-cassandra.json
commands.go:7:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
	/usr/local/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
	/root/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
2017-05-03 23:24:18,321 dcos-commons-test build & push script failed: ./frameworks/cassandra/build.sh invocation returned failure.  FAIL, aborting cassandra test```

**Comment by benclarkwood** [comment]
What tool did you use to do the vendoring?

The process needs to be documented as part of the CLI readme.

**Comment by ssk2** [comment]
@benclarkwood updated. cc @mrbrowning, I removed the invocation of `go test` which was in the wrong build.sh file since it wasn't happy about the vendoring.

**Comment by benclarkwood** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Comment by ssk2** [comment]
retest this please

**Pull request merged**
