### PR TITLE
HDFS-501: Backport HDFS-433 to sdk-0.40

### PR DESCRIPTION
**Pull request by porridge**
Clean cherry-pick.

### CODE REVIEW

**Comment by elezar** [comment]
Thanks @porridge.

Looking at the git logs between `master` and `sdk-0.40` it seems as if:
```
commit a22272f450919dc4695b5154920e0b2934bd009a
Author: Nima Vaziri <NimaVaziri@users.noreply.github.com>
Date:   Fri Feb 16 10:33:13 2018 -0800

    Removed update strategy as default should always be serial (#2272)
```
Could also be backported. I will create a separate ticket so as to keep the logs more comparable.

**Comment by elezar** [comment]
@porridge feel free to merge once the HDFS CI passes.

We may have to update the squash commit message and indicate that this should make it into the release notes.

**Comment by porridge** [comment]
@elezar is there a certain format I should follow w.r.t the message?

**Comment by porridge** [comment]
BTW, GitHub says ` You're not authorized to merge this pull request.`

**Comment by elezar** [comment]
With regards to:
> @elezar is there a certain format I should follow w.r.t the message?
No, not that I know of. We could just start with `RELEASE-NOTES:` or something?

Then:
> BTW, GitHub says `You're not authorized to merge this pull request.`
I have pinged @benclarkwood to add you to the team.

**Pull request merged**
