### PR TITLE
Prototype Framework

### PR DESCRIPTION
**Pull request by mohitsoni**
Prototype framework is a general purpose framework that takes a DC/OS service specification YAML and runs it as a managed, fault-tolerant, configurable and upgradable service.

### CODE REVIEW

**Comment by nickbp** [comment]
`frameworks/polymorph-framework`: naming is a little redundant

**Comment by mohitsoni** [comment]
@nickbp Dropped the `-framework` suffix

**Comment by nickbp** [comment]
Ping for review

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by gabrielhartmann** [comment]
@mohitsoni:  Can you change this to "SDK Proto-typer" or something like that.  This would be area help when iterating on an initial design.  Also catch it up to master please?

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by mohitsoni** [comment]
@mesosphere-ci retest this please

**Comment by triclambert** [comment]
retest this please

**Pull request merged**
