### PR TITLE
[INFINITY-1097] Add integration tests to hello-world FW

### PR DESCRIPTION
**Pull request by loren**
Port generic Cassandra shakedown tests to hello-world

- test_scheduler_died
- test_all_executors_killed
- test_master_killed
- test_zk_killed
- test_config_update_then_kill_task_in_node
- test_config_update_then_kill_all_task_in_node
- test_config_update_then_scheduler_died
- test_config_update_then_executor_killed
- test_config_update_then_all_executors_killed
- test_config_update_then_master_killed
- test_config_update_then_zk_killed
- DRY up bump_cpu_count_config functionality in hello-world test_sanity

Leaving out network partition tests for now, as they aren't working in hello-world and I'm not sure they are working anywhere.

### CODE REVIEW

**Comment by mrbrowning** [comment]
This looks good to me. How do we verify that tests don't pass spuriously, e.g. if we broke the plan endpoint so that it shows the old completed deploy plan even after initiation of a config update?

**Comment by gabrielhartmann** [comment]
@mrbrowning: Usually the way we check that is validate that TaskIDs change when expected, and don't change when not expected.

**Comment by loren** [comment]
@mrbrowning Did @gabrielhartmann address your concerns or am I cleared for Squash & Merge?

**Comment by loren** [comment]
retest this please

**Comment by loren** [comment]
retest this please

**Comment by loren** [comment]
retest this please because https://github.com/mesosphere/dcos-commons/commit/7c0d3213111f11f4c63d3a95ea330e1b72e23a2d

**Comment by loren** [comment]
retest this please ffs

**Comment by loren** [comment]
@mrbrowning or @nickbp , can one of you review this please?

**Comment by loren** [comment]
thank you @susanxhuynh for reviewing!

**Pull request merged**
