### PR TITLE
[INFINITY-1185] Rename DefaultPlanFactory to DeployPlanFactory

### PR DESCRIPTION
**Pull request by mgummelt**

### CODE REVIEW

**Comment by mrbrowning** [comment]
I'm not feeling dogmatic either way, but by this logic, should `DefaultPlan` also be moved to `DeployPlan`? The downside is that there would no longer be an obvious target to override for developers who want to reuse that logic in their custom plan definitions, which probably isn't worth the naming consistency between the factory and its product.

**Comment by mgummelt** [comment]
DefaultPlan isn't only used for deploys.  The `HDFSRecoveryPlanManager` uses it.

**Comment by mgummelt** [comment]
retest this please

**Comment by mgummelt** [comment]
The tests failed with some error during kafka install, but the logs are too sparse to diagnose.  Running again to repro.

**Comment by mgummelt** [comment]
network error

**Comment by mgummelt** [comment]
retest this please

**Pull request merged**
