### PR TITLE
Framework changes to be able to use DOCKER volumes in pods

### PR DESCRIPTION
**Pull request by disrani-px**
This is related to https://github.com/mesosphere/dcos-commons/issues/916

Changes also include updates for HDFS and Cassandra service to add DOCKER volume options. Default is still set to ROOT

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
Do the use of docker volumes require use of the Docker engine?

**Comment by disrani-px** [comment]
It would use dvdi for the docker volumes, not sure if that has a dependency on Docker engine.

**Comment by disrani-px** [comment]
Updated with feedback from the review and added some tests for the DockerVolumeSpec.

**Comment by keithchambers** [comment]
Hi Dinesh.

Thank you very much for contributing this PR. We are focusing on CSI in partnership
with the boarder container ecosystem: https://mesosphere.com/blog/2017/03/30/csi-towards-universal-storage-interface-for-containers. We are confident CSI as the path to supporting external volumes in this project. Is the Pirtworx team working on CSI?

Thanks,
Keith

**Comment by gourao** [comment]
Hi @keithchambers Yes, we are a coe part of the CSI effort, working with Ben and others on the core specs.  This PR is sort of unrelated to that in that, it only solves a current need for the DCOS ecosystem.  It is not incompatible with CSI, and to clarify that, when CSI gets ironed out and implemented, existing frameworks can and will migrate to that without impacting existing deployments.  

This PR is simply to allow existing DCOS users to deploy stateful applications while the internal plumbing gets sorted into a CNCF endorsed standard.

Hope that makes sense

**Comment by gourao** [comment]
@gabrielhartmann @disrani-px DVDI has no requirement of the Docker engine.

**Comment by keithchambers** [comment]
I understand the reasoning, but DVDI is not something we will support in our SDK. We will support CSI once available.

**Comment by gourao** [comment]
@keithchambers I understand your stance on closing the PR... we do have joint customers that need to deploy applications like cassandra, hdfs in production, today, with external volumes.  Would like to hear your recommendation for that.

**Pull request closed without merging**
