### PR TITLE
[INFINITY-1396] Remove unused MIGRATION labels

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by jasongilanfarr** [comment]
I couldn't find evidence that marathon actually reads these endpoints. It probably should... @aquamatthias ?

**Comment by aquamatthias** [comment]
@jasongilanfarr the readiness check defines the contract (incl. path etc). Marathon still has checks for the tags: https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L484

**Comment by jasongilanfarr** [comment]
I know that we have the validation checks, but i didn't see us actually _use_ the fields.

**Comment by aquamatthias** [comment]
It is used by the UI to query the plan and do the proceed operations.

**Comment by gabrielhartmann** [comment]
The DC/OS UI team doesn't use this.

**Pull request merged**
