### PR TITLE
Supply Reconciler with TaskStatusProvider in constructor and remove from arguments in start method

### PR DESCRIPTION
**Pull request by mrbrowning**
To ensure that task statuses are all coming from a single source of truth, this alters the `Reconciler` interface so that the `start()` method no longer accepts a list of `TaskStatus` protos. Instead, it is expected that the implementing class will accept a `TaskStatusProvider` in its constructor, which it will consult to fetch a collection of all task statuses currently known by the scheduler. To this end, the `StateStore` interface now extends the `TaskStatusProvider` interface with its `getTaskStatuses()` method. All default implementations of these interfaces now reflect the new semantics.

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@mrbrowning:  Tests failing?  Also this PR will need to bump `build.gradle` version.

**Comment by mrbrowning** [comment]
@gabrielhartmann Tests are passing.

**Comment by gabrielhartmann** [comment]
@mrbrowning:  Unit test failing.

**Comment by gabrielhartmann** [comment]
@mrbrowning:  I this for INFINITY-321 ?

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Pull request merged**
