### PR TITLE
DCOS_ELASTIC-21 Adding support for Kibana Plugins and therefore also …

### PR DESCRIPTION
**Pull request by devpie**
…increasing the grace period.

### CODE REVIEW

**Comment by devpie** [comment]
Hi, would somebody tell me why all the checks fail?

**Comment by elezar** [comment]
For security reasons, we don't by default allow external contributions to trigger our CI.

**Comment by jan-ruv** [comment]
Ah ok, thanks. That makes sense :smile:

**Comment by keithchambers** [comment]
Hi Jan. Thank you for the PR. This is something that aligns with our roadmap.

Let me check with Engineering to see if they can code review and if anything is missing. Get back with you shortly ...

**Comment by vishnu2kmohan** [comment]
@mpereira Does this make sense for us to include this (if this is not already the case) for our Elastic 6.6 release?
cc @imaxxs

**Comment by mpereira** [comment]
@vishnu2kmohan it does. I added https://jira.mesosphere.com/browse/DCOS-39949 to the current sprint. It's already under the Elastic 6.6.0 epic.

**Comment by takirala** [comment]
Elastic framework has been moved to https://github.com/mesosphere/dcos-elastic-service

**Pull request closed without merging**
