### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by nickbp** [comment]
Lost in merge: upgrade test https://github.com/mesosphere/dcos-commons/pull/294

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
@nickbp: Working on the lost upgrade test in another PR.  Trying to unblock all PRs now.

**Pull request merged**
