### PR TITLE
Update kafka 1.1.0

### PR DESCRIPTION
**Pull request by Gupta-Amrit**
Updating kafka base tech from kafka 1.0.0 to kafka 1.1.0

### CODE REVIEW

**Comment by porridge** [comment]
@samvantran I don't understand why this was merged despite failing `infinity/kafka` teamcity tests?
This broke our CI: https://jira.mesosphere.com/browse/DCOS-38318

**Comment by samvantran** [comment]
@porridge sorry that was a bad call on my side. I had saw the previous two merged PRs had failing kafka CI tests and assumed that it was a known issue, plus this PR had already been approved by Ben so I decided to merge. My main intention was to get this in to backport to sdk040 so that we could soak and test it working.

Thanks for reverting though and I'll dig into why Kafka is causing those auth issues.

**Comment by benclarkwood** [comment]
@samvantran which two previous PRs?

**Comment by samvantran** [comment]
#2524 & #2527 - these were merged to master before this one

**Comment by elezar** [comment]
Yes, there are known Kafka and Elastic issues tracked in two JIRA tickets: https://jira.mesosphere.com/browse/DCOS-38235 https://jira.mesosphere.com/browse/DCOS-38238, respectively which also failed for the two PRs mentioned. We do sometimes make a decision to override these checks -- especially if these seem to be upstream issues, but we should limit this and only do so after we've confirmed an existing issue that is tracked in a JIRA ticket.

**Comment by porridge** [comment]
I'd add a requirement to mention relevant Jira ID in a PR comment right
before hitting the merge button in such case.

**Comment by elezar** [comment]
Yes, for DC/OS PRs they use mergebot to link the JIRA tickets to the github overrides.

**Pull request merged**
