### PR TITLE
[SDK] New StateStore with a filter to ignore old TaskInfo and TaskStatus.

### PR DESCRIPTION
**Pull request by mbdcos**
Config *Upgrade* should be able to handle old and new tasks in StateStore (they have different names and TaskInfo is different, Specs are different) at the same time. Best way is to filter somehow. Not only status update is affected by this, also recovery process will be affected (will try to update old tasks that are only kept for backup/restore).  

Below is an example on how a service can use Ignore filter:

CuratorStateStoreFilter stateStore = new CuratorStateStoreFilter(schedulerBuilder.getServiceSpec().getName(),
                        DcosConstants.MESOS_MASTER_ZK_CONNECTION_STRING);
stateStore.setIgnoreFilter(RegexMatcher.create( "broker-[0-9]*"));
schedulerBuilder.setStateStore(StateStoreCache.getInstance(stateStore));

### CODE REVIEW

**Comment by mohitsoni** [comment]
@mbdcos What's the context behind this PR ? Can you please provide that in the description ?

**Comment by mohitsoni** [comment]
@mbdcos Also, can you please add unit tests for this PR ?

**Comment by mbdcos** [comment]
CuratorStateStoreFilterTest

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@mbdcos:  Please re-open if this is still needed, otherwise please delete the branch.

**Pull request closed without merging**
