### PR TITLE
[ELASTIC] Expose transport endpoints via VIPs

### LINKED ISSUE #649: [ELASTIC] Expose elasticsearch transport endpoint via VIPs
Elasticsearch supports a transport client [1] that connects to the transport endpoint (port 9300) instead of the HTTP endpoint (port 9200). This endpoint should be exposed via VIPs to enable containers to connect via the transport protocol.

[1] https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/transport-client.html

### PR DESCRIPTION
**Pull request by liorze**
Fixes #649

### CODE REVIEW

**Comment by ssiahetiong** [comment]
any updates on this?

**Comment by loren** [comment]
@ssiahetiong I'm sorry for the delay on this.
@liorze Can you please rebase this on master so we can kick off an up-to-date Continuous Integration run?

**Comment by ssiahetiong** [comment]
i tried manually applying the patch,but seems my app can't connect via the tcp, did ot work for you @liorze

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@loren: Have you given this a try and verified that `dcos elastic endpoints` shows the right thing.  If it does I say :shipit: .

**Pull request merged**
