### PR TITLE
Add seeds endpoint to cassandra scheduler

### PR DESCRIPTION
**Pull request by mrbrowning**
This adds an endpoint at `/v1/seeds` that accepts `GET` requests, as well as endpoints at `/v1/seeds/<datacenter` that accept `PUT` requests for each remote datacenter configured, for the retrieval/update of local and remote seeds, respectively. Missing pieces right now are just the plumbing through of configuration options for number of seeds and remote datacenter names/URLs to the `SeedsResource` setup in `CassandraService`. I have tentative work for this in the upcoming PR for the seed provider itself, but this work raised the question of how to get that config to the `SeedsResource`, since `DefaultScheduler` doesn't expose it. Rather than do a bunch of plumbing to expose the `ConfigStore` outside of `DefaultScheduler`, I'm thinking that the most reasonable option involves accessing these configuration options directly via environment variables or Java system properties passed as flags to the command, but I'm curious what opinions on that are.

### CODE REVIEW

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by mrbrowning** [comment]
Fixed underlying Cassandra config bug in #762 , but master was broken last time due to a bad merge.

**Comment by nickbp** [comment]
Anything missing here? Feels like DefaultScheduler.Builder should have an explicit function to pass in custom API resources, but I see this is duplicating what Kafka currently does so LGTM.

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by mrbrowning** [comment]
The Mesosphere maven repo is being uncooperative.

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Pull request merged**
