### PR TITLE
[KAFKA][KAF-297] Disable JMX and STATSD options 

### PR DESCRIPTION
**Pull request by mbdcos**

### CODE REVIEW

**Comment by mbdcos** [comment]
Do not merge this yet.

**Comment by keithchambers** [comment]
LGTM

**Comment by gabrielhartmann** [comment]
@mbdcos:  Please resolve conflicts and merge.

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Pull request merged**
