### PR TITLE
Bump the JRE to 1.8 u171

### PR DESCRIPTION
**Pull request by benclarkwood**

### CODE REVIEW

**Comment by vishnu2kmohan** [comment]
+1 for 8u172

**Comment by benclarkwood** [comment]
The guidance from Oracle is to consume the CPU unless you know you need something in the PSU.

http://www.oracle.com/technetwork/java/javase/8u172-relnotes-4308893.html. There also isn't much in the PSU.

**Comment by benclarkwood** [comment]
But I'm a people pleaser, so the people shall receive that which they've asked for.

**Comment by mpereira** [comment]
HW `test_resource_refinement.test_marathon_volume_collission` seems to be failing consistently with this branch.

**Comment by benclarkwood** [comment]
@mpereira it's definitely increasingly flaky.

cc @kvish

**Pull request merged**
