### PR TITLE
[INFINITY-2713] Update the JRE and JCE to 1.8_152

### PR DESCRIPTION
**Pull request by benclarkwood**

### CODE REVIEW

**Comment by mpereira** [comment]
I noticed a few more references to JRE/JCE artifacts in test config files and documentation, does it matter if those aren't changed? 

```
./cli/commands/testdata/responses/cosmos/1.10/enterprise/describe-no-package-versions.json:152:          "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u131-linux-x64.tar.gz",
./cli/commands/testdata/responses/cosmos/1.10/enterprise/describe.json:152:          "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u131-linux-x64.tar.gz",
./cli/commands/testdata/responses/cosmos/1.10/enterprise/update.json:152:          "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u131-linux-x64.tar.gz",
./cli/commands/testdata/responses/cosmos/1.10/open/describe.json:152:          "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u131-linux-x64.tar.gz",
./frameworks/hdfs/docs/api-reference.md:462:					value: "https://downloads.mesosphere.com/java/jre-8u112-linux-x64-jce-unlimited.tar.gz",
./frameworks/hdfs/docs/managing.md:755:              "value": "https://downloads.mesosphere.com/java/jre-8u112-linux-x64-jce-unlimited.tar.gz",
./frameworks/kafka/docs/kerberos.md:175:    wget https://downloads.mesosphere.com/java/jre-8u131-linux-x64-jce-unlimited.tar.gz && \
./frameworks/kafka/docs/kerberos.md:176:    tar -xzvf jre-8u131-linux-x64-jce-unlimited.tar.gz && \
./frameworks/kafka/docs/kerberos.md:177:    rm jre-8u131-linux-x64-jce-unlimited.tar.gz
```

**Comment by benclarkwood** [comment]
@mpereira Good catch.

@elezar why are we referencing a JRE in the kerb docs?
@NimaVaziri why are we referencing a JRE in those two HDFS docs?

**Comment by elezar** [comment]
The reference in the Kerberos docs are because the standard docker image described does not include the JCE and it needs to be downloaded.

**Comment by elezar** [comment]
The references to the version have been moved from the Kafka kerberos docs.

**Comment by benclarkwood** [comment]
@elezar plz spawn a ticket to investigate that.

**Comment by elezar** [comment]
Done.

**Comment by benclarkwood** [comment]
@elezar But what ticket tho

**Pull request merged**
