### PR TITLE
[INFINITY-2102] Set minDcosVersion to 1.9 where appropriate

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by elezar** [comment]
Looks good:
```
grep -R minDcosReleaseVersion .
./cli/commands/testdata/responses/cosmos/1.10/enterprise/describe-no-package-versions.json:    "minDcosReleaseVersion": "1.10",
./cli/commands/testdata/responses/cosmos/1.10/enterprise/describe.json:    "minDcosReleaseVersion": "1.10",
./cli/commands/testdata/responses/cosmos/1.10/enterprise/update.json:    "minDcosReleaseVersion": "1.9",
./cli/commands/testdata/responses/cosmos/1.10/open/describe.json:    "minDcosReleaseVersion": "1.9",
./frameworks/cassandra/universe/package.json:  "minDcosReleaseVersion": "1.8",
./frameworks/elastic/universe/package.json:  "minDcosReleaseVersion": "1.9",
./frameworks/elastic/universe-kibana/package.json:  "minDcosReleaseVersion": "1.9",
./frameworks/hdfs/universe/package.json:  "minDcosReleaseVersion": "1.9",
./frameworks/helloworld/universe/package.json:  "minDcosReleaseVersion": "1.9",
./frameworks/kafka/universe/package.json:  "minDcosReleaseVersion": "1.9",
./frameworks/template/universe/package.json:  "minDcosReleaseVersion": "1.9",
./tools/README.md:- `MIN_DCOS_RELEASE_VERSION` (default: 1.7): The value of `minDcosReleaseVersion` to use for the released package, or `0` to set no value. See [universe documentation](https://github.com/mesosphere/universe) for more details on this value.
./tools/release_builder.py:            if 'minDcosReleaseVersion' not in content_json:
./tools/release_builder.py:                raise Exception('minDcosReleaseVersion must be specified in package.json: {}'.format(content_json))
```
Would it make sense to update the docs (referring to 1.7) in this PR too?

Also, to be clear, the kafka package here has a minimum version of 1.9 whereas confluent-kafka has a minimum verison of 1.8?

**Comment by elezar** [comment]
Is this also the PR where we would disable the tests for the unsupported versions? Where would that be configured?

**Comment by benclarkwood** [comment]
@elezar That's out of band TC stuff. I already did that.

**Comment by gabrielhartmann** [comment]
@elezar and @benclarkwood:  Actually I keep forgetting this can't be merged until we can test on 1.8 and 1.9... so I'll close for now and revisit later.

**Pull request closed without merging**
