### PR TITLE
Backport NPE fix to 0.8.1 as 0.8.1.1

### PR DESCRIPTION
**Pull request by gabrielhartmann**
Fix to backport is: 8c493ceceb00ec32d2a7eadd7823e696deafccf8

### CODE REVIEW

**Comment by mgummelt** [comment]
Why merge this into master?  We should leave it as it's own branch.

**Comment by gabrielhartmann** [comment]
@mgummelt:  I don't intend to merge to master.  This is for review.  It will be on tag `0.8.1.1`

**Comment by mgummelt** [comment]
Oh, you can just submit the branch and link the reviewer to the commits if that's what you intend.

LGTM

**Comment by gabrielhartmann** [comment]
Thanks @nickbp and @mgummelt for review.

**Pull request closed without merging**
