### PR TITLE
Fix CI error tools/piputil.py

### PR DESCRIPTION
**Pull request by mbdcos**

### CODE REVIEW

**Comment by jsrodman** [comment]
Not sure why this error isn't seen elsewhere, but it's probably better to use b'python 3' if it's reliably a byte string.  I thought i checked the output value though.

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
Byte or string, should be same type. You already have pip3 command, it will return before, so you do not see this error.

**Comment by mbdcos** [comment]
@nickbp already fixed this. Closing....

**Pull request closed without merging**
