### PR TITLE
Fix NullPointerException when agent is restarted and CustomExecutor

### PR DESCRIPTION
**Pull request by verma7**
re-registers

### CODE REVIEW

**Comment by verma7** [comment]
Fixes #372.

**Comment by verma7** [comment]
@mgummelt @gabrielhartmann

**Comment by mgummelt** [comment]
Do you have the full logs during the NPE?  `reregistered` should always be called after `registered` (where `executorInfo` is set), so this is unexpected.

**Comment by verma7** [comment]
You can easily reproduce the problem by restarting the agent on which the Cassandra task is running. 

Here's the agent stderr:
```
I1203 01:42:22.362025   820 exec.cpp:161] Version: 1.0.1-uber2-42
I1203 01:42:22.365764   789 exec.cpp:236] Executor registered on agent e6e07ff7-d0ff-4f57-a2b3-5e1929635a3f-S1254
I1209 01:25:56.754560   790 exec.cpp:486] Agent exited, but framework has checkpointing enabled. Waiting 365days to reconnect with agent e6e07ff7-d0ff-4f57-a2b3-5e1929635a3f-S1254
I1209 01:25:57.062994   801 exec.cpp:282] Received reconnect request from agent e6e07ff7-d0ff-4f57-a2b3-5e1929635a3f-S1254
I1209 01:25:57.075634   792 exec.cpp:259] Executor re-registered on agent e6e07ff7-d0ff-4f57-a2b3-5e1929635a3f-S1254
java.lang.NullPointerException
	at org.apache.mesos.executor.CustomExecutor.reregistered(CustomExecutor.java:52)
	at com.mesosphere.dcos.cassandra.executor.CassandraExecutor.reregistered(CassandraExecutor.java:75)
Exception in thread "Thread-8668" I1209 01:25:57.079258   792 exec.cpp:448] Deactivating the executor libprocess
```

stdout:
```
INFO  [2016-12-03 01:42:39,695] com.mesosphere.dcos.cassandra.executor.Probe: Connection to server failed backing off for 500 ms
INFO  [2016-12-03 01:42:40,244] com.mesosphere.dcos.cassandra.executor.Probe: Node probe is successfully connected to the Cassandra Daemon: port 7199
INFO  [2016-12-03 01:42:42,628] com.mesosphere.dcos.cassandra.executor.CassandraDaemonProcess: Cassandra Daemon mode = NORMAL
INFO  [2016-12-03 01:42:42,681] com.mesosphere.dcos.cassandra.executor.CassandraDaemonProcess: Sent status update = task_id { value: "node-4__1d87f22c-e9ae-44f5-8e3a-5543e2046e60" } state: TASK_RUNNING data: "\b\000`\002h\000" message: "Cassandra Daemon running." slave_id { value: "e6e07ff7-d0ff-4f57-a2b3-5e1929635a3f-S1254" } executor_id { value: "node-4_executor__16700eaf-d244-4a48-ad24-ff71b2c7f921" } source: SOURCE_EXECUTOR 
INFO  [2016-12-09 01:25:57,079] com.mesosphere.dcos.cassandra.executor.ExecutorDriverDispatcher: Driver execution complete status = DRIVER_ABORTED
INFO  [2016-12-09 01:25:57,178] org.eclipse.jetty.server.ServerConnector: Stopped DCOS Cassandra Executor@7af1cd63{HTTP/1.1}{0.0.0.0:31001}
INFO  [2016-12-09 01:25:57,180] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@44b18fe4{/admin,null,UNAVAILABLE}
INFO  [2016-12-09 01:25:57,184] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@3c69362a{/,null,UNAVAILABLE}
INFO  [2016-12-09 01:25:57,185] com.mesosphere.dcos.cassandra.executor.ExecutorDriverDispatcher: Stopping ExecutorDriver
```

**Comment by mgummelt** [comment]
Sure enough.  For some reason, the `registered` callback isn't being called, which is the source of this NPE.  I'm fine merging this to fix the immediate problem, though.

**Pull request merged**
