### PR TITLE
[ELASTIC-45] Fix Elastic CLI help errors

### PR DESCRIPTION
**Pull request by loren**
- Changed boilerplate text
- Removed unused example section

### CODE REVIEW

**Comment by loren** [comment]
retest this please

**Comment by keithchambers** [comment]
@triclambert I suspect most developers that use our SDK will miss this. Instead of solving this for Elastic, how about we eliminate the command description (e.g., "Provides an example for DC/OS service developers") altogether? Same thing for removing (or commenting out) the Example commands.

**Comment by nickbp** [comment]
FWIW I did some of that so far, specifically removing the 'Example' sections, in #589 .

While I didn't remove the description strings in that PR, I agree that it'd also make sense to remove them as they're not really helpful to users and are yet another thing for a new developer to worry about updating

**Comment by nickbp** [comment]
I'll do the remaining cleanup in a separte PR (tracking: INFINITY-1093)

**Pull request merged**
