### PR TITLE
Steps should proceed when restarted too. Plus a unit test alteration.

### PR DESCRIPTION
**Pull request by ssk2**

### CODE REVIEW

**Comment by ssk2** [comment]
retest this please

**Comment by benclarkwood** [comment]
Wait. How is it... just a unit test alteration?

**Comment by ssk2** [comment]
@benclarkwood, I must have fixed the proceed thing in another PR after this.

**Comment by ssk2** [comment]
But not the unit tests...

**Comment by ssk2** [comment]
Alright, this is taking too much effort to get reviewed for a (now) two line change. I'm merging.

**Comment by gabrielhartmann** [comment]
@ssk2:  Was just about to review!

**Pull request merged**
