### PR TITLE
Revert buggy url parsing patch

### PR DESCRIPTION
**Pull request by nlsun**
My previous patch actually broke it.

### CODE REVIEW

**Comment by nlsun** [comment]
@ssk2 we just discovered that this actually breaks it because the expected url is minus one `/`. Right after I pinged to merge too... Sorry about this.

**Comment by nlsun** [comment]
hold on, still buggy

**Comment by nlsun** [comment]
ok, thinking about it more, the original behavior was probably the more correct one, as a url with both "/" and "/#/" will get trimmed.

It may actually be better to just revert my previous patch.

Also, an unsolicited suggestion, is to not be modifying global state in `"github.com/mesosphere/dcos-commons/cli/config"`

**Comment by benclarkwood** [comment]
@nlsun Yes please submit a reversion patch.

And yes, I agree we do weird things to the config state. CLI code is in a state of flux currently.

**Comment by nlsun** [comment]
Changed to a git revert

**Comment by benclarkwood** [comment]
retest this please

**Pull request merged**
