### PR TITLE
Fix EE check

### PR DESCRIPTION
**Pull request by benclarkwood**
pytest skipif is not correctly setup.

Add function invocation.

### CODE REVIEW

**Comment by benclarkwood** [comment]
[Fix EE check](https://trello.com/c/riHy9Nex/20-fix-ee-check)

**Comment by elezar** [comment]
@benclarkwood @mhrabovcin there was an error in the parameter order for the cassandra install step. I have pushed a change to correct this.

**Comment by elezar** [comment]
@benclarkwood @mhrabovcin The Cassandra TLS test now fails. I see an error in the logs regarding the `.ssl` directory in the `MESOS_SANDBOX` not being found. Is there some PR out that should fix this?

**Comment by benclarkwood** [comment]
I hadn't had a chance to circle back around to this.

@mhrabovcin, I saw some rumblings somewhere that this directory has disappeared? Don't we rely on it for all sorts of things?

**Comment by elezar** [comment]
Just remembered that Martin is on leave this week.

**Pull request merged**
