### PR TITLE
[SDK/CLI] In 'plans' RPC, allow both UUIDs and names when specifying plans/steps

### PR DESCRIPTION
**Pull request by nickbp**
- Better test coverage in PlansResource
- Update CLI to reflect previous PlansResource changes
- Update swagger spec to reflect previous PlansResource changes
- Make continue/interrupt phase argument consistent with other commands: provide phase as a query param instead of a path param (avoids problems with phases named 'start', 'stop', 'continue', 'interrupt', 'forceComplete', or 'restart')

### CODE REVIEW

**Comment by nickbp** [comment]
Looks like there isn't a lot of mention of plan operations in general, but updated mentions of interrupt/continue in the dev guide to mention the availability of per-phase granularity.

**Comment by mbdcos** [comment]
LGTM

**Comment by nickbp** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Pull request merged**
