### PR TITLE
Add boto to test deps

### PR DESCRIPTION
**Pull request by mgummelt**
cc @jsrodman 

Spark tests require boto

### CODE REVIEW

**Comment by jsrodman** [comment]
Do you prefer this over providing a requirements file?  That's sort of why the requirements file interface exists, but I don't think this causes any harm.

**Comment by mgummelt** [comment]
I'd prefer to provide a requirements file so I can keep Spark's requirements separate.  Is there a way to do that currently?

**Comment by jsrodman** [comment]
run_tests.py takes a requirements file as an argument, which overrides the inline generated requirements file.
It's good to have an internal user too, we weren't really validating the codepath by any means, and it's pretty much intended for partners.

**Comment by mgummelt** [comment]
OK, great, I'll do that.

BTW, even after I make Spark use `run_tests.py`, there's still opportunity for further consolidation with `dcos-commons`.  Ideally, I would just build the Spark package, then run some script like `test.py STUB_UNIVERSE_URL /path/to/tests`, which would start a cluster and run the tests.

The problem is that, currently, starting a cluster and building the framework are coupled together in `dcos-commons/test.sh`.  If you could factor that out, it would go a long way towards reducing duplication.

**Comment by jsrodman** [comment]
I'm not sure why framework builds happened in test.sh in general.  However, dcos-commons/test.py --test-only already skips builds, but the interface for finding out the stub universe url is still a hack bound fairly tightly to the test.py build step.  In other words, it assumes a temp file will still exist somewhere with the url in it.

**Pull request closed without merging**
