### PR TITLE
Fix pod not exiting when a task fails

### PR DESCRIPTION
**Pull request by nickbp**

### CODE REVIEW

**Comment by nickbp** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by benclarkwood** [comment]
restart this please

**Comment by benclarkwood** [comment]
restart this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Pull request merged**
