### PR TITLE
Remove feature maturity flag

### PR DESCRIPTION
**Pull request by sascala**
cc/ @YrieixGarnier @keithchambers

### CODE REVIEW

**Comment by triclambert** [comment]
There are still quite a few mentions missing...
```
~/workspace/dcos-commons (ss/remove-preview) $ grep -RiI 'feature_maturity: preview' * | wc -l
      14
```

**Comment by keithchambers** [comment]
+1 for removing "Feature Maturity".

**Comment by elezar** [comment]
Just checking, should **all** `feature_maturity` tags be removed?

@sascala I can push the changes (with a merged master) if that helps to get this done?

**Comment by sascala** [comment]
Of course, Evan, feel free.

**Comment by elezar** [comment]
(I think @paegun already has most of them done in #1598. Let's merge that)

**Pull request merged**
