### PR TITLE
[INFINITY-1392] Handle minor version numbers of clusters.

### PR DESCRIPTION
**Pull request by jsrodman**
DSE actually ran into this :-(

### CODE REVIEW

**Comment by benclarkwood** [comment]
@jsrodman Looks good. Rebase and shepherd through CI.

**Comment by jsrodman** [comment]
retest this please

**Comment by jsrodman** [comment]
ironically; this failed on something else I haven't finished the PR for.

**Comment by benclarkwood** [comment]
What did it fail on? JIRA ticket?

**Comment by jsrodman** [comment]
I thought it was another manifestation of KAF-326.  Now I'm not so sure.

**Pull request merged**
