### PR TITLE
Use repeated -p parameter for specifying plan envvars

### PR DESCRIPTION
**Pull request by mrbrowning**
Manually verified that this works as expected with single and multi-parameter plans.

### CODE REVIEW

**Comment by mrbrowning** [comment]
@benclarkwood I think supplying these optionally as JSON is a great idea too, but this interface will continue to be useful for simpler plans, and I needed it quickly because of the existing way's stupid handling of values that have `"="` in them, as many base64-encoded values do.

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by gabrielhartmann** [comment]
@mrbrowning I agree that this change is valuable on its own.  It will be nice to have a JSON option in the future, but this need not be blocked by that.  Do you have a JIRA for that work?

**Comment by mrbrowning** [comment]
I agree that some tests of this particular function are useful, but in general I think we should be judicious in spending time on a unit test suite for the CLI package. It's mostly stable, it's very simple, and although (as a user-facing component) it not breaking is a high priority, a CLI bug is not show-stopping given the availability of the HTTP API. These are all factors that diminish the likely value of a rigorous test suite, so I don't think anyone need spend hours chasing coverage here.

**Comment by mrbrowning** [comment]
@jsrodman do you think it would be appropriate for CLI unit tests to be run in `build.sh`? Currently we only build the CLI package on a per-framework basis, so I'm not sure if the assumptions about the environment `build.sh` is running in will check out.

**Comment by jsrodman** [comment]
@mrbrowning Sounds good to me, and all builds are running on the 'infinity' image, so it shouidln't break.

**Comment by mrbrowning** [comment]
@mesosphere-ci retest this please

**Comment by benclarkwood** [comment]
@mrbrowning Agreed that the CLI need not be exhaustively tested. I think a good rule of thumb is tests around user input to ensure good UX. WDYT?

Thank you for setting this up!

**Pull request merged**
