### PR TITLE
Revert "[INFINITY-1427] rollback ci (#934)"

### PR DESCRIPTION
**Pull request by jsrodman**
This reverts commit b453585db0d0bddbceec48bf40be271a9716512c.

### CODE REVIEW

**Comment by jsrodman** [comment]
retest this please

**Comment by nickbp** [comment]
ping

**Comment by jsrodman** [comment]
@nickbp this is blocked on https://jira.mesosphere.com/browse/INFINITY-1675 essentially.  I can close it for now if that helps?

**Comment by nickbp** [comment]
was just going through PRs that hadn't moved for a while, feel free to close if it's out of date (or keep open if it's still WIP)

**Comment by benclarkwood** [comment]
This seems out of date. If not out of date, feel free to re-open.

**Pull request closed without merging**
