### PR TITLE
[CASSANDRA-554] Remove JMX and Remote Statsd from new SDK based Cassandra Service

### PR DESCRIPTION
**Pull request by benclarkwood**
Setup Cassandra to report metrics to DC/OS StatsD.

### CODE REVIEW

**Comment by benclarkwood** [comment]
@keithchambers The only configurable statsd thing is the reporting period (defaults to 60 seconds).

Deprecation notice is a separate PR against dcos-cassandra-service.

**Comment by keithchambers** [comment]
Based on my understanding of how DC/OS Metrics works, changing the sample rate will have little effect since the DC/OS Metrics Agent caches the latest value and an http client needs to pool the metrics API (likely at some interval) to fetch the latest value.

Can you check with Jeff to understand if changing the sample rate will deliver enough customer value or if it would be acceptable to KISS and hard code to a value like 15 seconds?

**Comment by benclarkwood** [comment]
Checking with Jeff

**Comment by benclarkwood** [comment]
@keithchambers Jeff says:

Jeff Malnick [9:38 AM] 
The metrics service only exposes the latest values, we don't cache (yet).
So send as often as you want to scrap the HTTP API where it's exposed

Which makes me think it is a useful knob to have exposed.

**Comment by benclarkwood** [comment]
Talked with Keith. We're going to go with a hardcoded 10 second default.

**Comment by benclarkwood** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@benclarkwood:  Where is the 10s hard-coded?

**Pull request merged**
