### PR TITLE
Expose additional subtypes for Jackson in ScheduleBuilder

### PR DESCRIPTION
**Pull request by jimmidyson**
As discussed on Slack.

### CODE REVIEW

**Comment by jimmidyson** [comment]
@benclarkwood Any chance of merging this?

**Comment by benclarkwood** [comment]
@jimmidyson re-running HW

Will merge when it passes.

**Comment by benclarkwood** [comment]
Hm. Something is screwy with HW. Testing it locally.

**Comment by benclarkwood** [comment]
Hm. Something is screwy with HW. Testing it locally.

**Comment by benclarkwood** [comment]
This is blocked by upstream brokeness. I'm merging it.

**Pull request merged**
