### PR TITLE
[KAF-327] Wait till all brokers register after replace

### PR DESCRIPTION
**Pull request by mbdcos**
Create topic fails sometimes, saying that "replication factor: 3 larger than available brokers: 2"

### CODE REVIEW

**Comment by jsrodman** [comment]
Okay, so test_topic_create has been occasionally been failing, and this is trying to be safer about ensuring that test_pods_restart has fully completed before continuing.  Makes sense to me.

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
Waiting CI to be fixed.

**Pull request merged**
