### PR TITLE
[WIP] Fix flaky Hdfs data integrity test

### PR DESCRIPTION
**Pull request by susanxhuynh**

### CODE REVIEW

**Comment by susanxhuynh** [comment]
retest this please

**Comment by susanxhuynh** [comment]
retest this please

**Comment by susanxhuynh** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@susanxhuynh:  Is this ready to go?

**Comment by susanxhuynh** [comment]
@gabrielhartmann  No, it failed 1 out of 4 Jenkins test runs. I suspect because there's no readiness check, the HDFS write which runs immediately after the install fails sometimes. I guess it does decrease the error rate somewhat. For now, these tests are marked skip.

**Comment by susanxhuynh** [comment]
retest this please

**Comment by susanxhuynh** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@susanxhuynh:  This should not be needed due to #472.  Please re-open if this isn't true.

**Pull request closed without merging**
