### PR TITLE
Rlimit parameters are added to the elastic configuration.

### PR DESCRIPTION
**Pull request by AnandJat**
RLIMT_STACK , RLIMIT_NPROC , RLIMT_MEMLOCK has been implemented with in elastic with the value by which elastic service getting up and running successfully.

### CODE REVIEW

**Comment by AnandJat** [comment]
Closing this PR as code check is failing

**Comment by AnandJat** [comment]
Will fix code check in same PR.

**Comment by samvantran** [comment]
Hm, this is kind of tricky at this current moment. Due to Elastic repo currently in-transit to a new repo and CI pipeline, we aren't checking to see if the tests you created are actually run.

Can you continue the work but for another FW inside of dcos-commons? Like Cassandra or HDFS?

**Comment by AnandJat** [comment]
Okay, RLIMIT in Cassandra already done with test cases and today will work on HDFS. Should I Raised new PR for Cassandra so that logic can be reviewed ? Or all remaining framework in single PR?

**Comment by mpereira** [comment]
Elastic was [moved](https://github.com/mesosphere/dcos-commons/pull/3107) to [dcos-elastic-service](https://github.com/mesosphere/dcos-elastic-service), please open your PR there instead.

**Pull request closed without merging**
