### PR TITLE
[INFINITY-2038] Support data_center and rack configuration in Cassandra

### PR DESCRIPTION
**Pull request by mbdcos**

### CODE REVIEW

**Comment by mbdcos** [comment]
```
#
# Out of the box, Cassandra provides
#  - SimpleSnitch:
#    Treats Strategy order as proximity. This can improve cache
#    locality when disabling read repair.  Only appropriate for
#    single-datacenter deployments.
#  - GossipingPropertyFileSnitch
#    This should be your go-to snitch for production use.  The rack
#    and datacenter for the local node are defined in
#    cassandra-rackdc.properties and propagated to other nodes via
#    gossip.  If cassandra-topology.properties exists, it is used as a
#    fallback, allowing migration from the PropertyFileSnitch.
#  - PropertyFileSnitch:
#    Proximity is determined by rack and data center, which are
#    explicitly configured in cassandra-topology.properties.
#  - Ec2Snitch:
#    Appropriate for EC2 deployments in a single Region. Loads Region
#    and Availability Zone information from the EC2 API. The Region is
#    treated as the datacenter, and the Availability Zone as the rack.
#    Only private IPs are used, so this will not work across multiple
#    Regions.
#  - Ec2MultiRegionSnitch:
#    Uses public IPs as broadcast_address to allow cross-region
#    connectivity.  (Thus, you should set seed addresses to the public
#    IP as well.) You will need to open the storage_port or
#    ssl_storage_port on the public IP firewall.  (For intra-Region
#    traffic, Cassandra will switch to the private IP after
#    establishing a connection.)
#  - RackInferringSnitch:
#    Proximity is determined by rack and data center, which are
#    assumed to correspond to the 3rd and 2nd octet of each node's IP
#    address, respectively.  Unless this happens to match your
#    deployment conventions, this is best used as an example of
#    writing a custom Snitch class and is provided in that spirit.
#
```

**Comment by mbdcos** [comment]
http://docs.datastax.com/en/cassandra/2.1/cassandra/architecture/architectureSnitchGossipPF_c.html

**Comment by mbdcos** [comment]
1) DATA_CENTER and RACK_ID env vars were only local to scheduler.
2) Template was missing for cassandra-rackdc.properties
3) cassandra.yml configuration was using SimpleSnitch

**Comment by mbdcos** [comment]
Who is the Cassandra expert for multi data center configuration?

**Comment by benclarkwood** [comment]
@mrbrowning and @gabrielhartmann have probably done it the most on our team? We can also ask Datastax.

**Comment by benclarkwood** [comment]
@mbdcos Do we have a multi-dc test?

**Comment by mbdcos** [comment]
@benclarkwood I do not see any

**Comment by mbdcos** [comment]
```
$ cat options.json 
{
  "service": {
    "name": "cassandra-mb",
    "data_center": "mb-data-center"
  }
}

$ dcos package install  cassandra --options=options.json  --yes
# node 0
$ dcos node ssh --master-proxy --mesos-id 14f2df6a-3456-42a1-b9a1-aafd96c56d94-S3 
docker run --net=host -ti cassandra:3.0.12 nodetool status
 
Datacenter: mb-data-center
==========================
```

**Comment by triclambert** [comment]
> Do we have a multi-dc test?
Please add some.

**Comment by mbdcos** [comment]
@triclambert Please open a ticket for multi data center tests separate from this PR. It is a major task.

**Comment by mbdcos** [comment]
```
$ cat options.json 
{
  "service": {
    "name": "cassandra-mb",
    "data_center": "mb-data-center",
    "rack": "mb-rack-9"
  }
}

node-0-server agent: 

docker run --net=host -ti cassandra:3.0.12 nodetool status

Datacenter: mb-data-center
==========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.0.0.9    79.69 KB   256          100.0%            6c4d999c-f281-447f-8b84-60d54136eb6f  mb-rack-9
UN  10.0.1.254  96.34 KB   256          100.0%            3ad4753f-940d-44eb-9341-e9b51a58ff27  mb-rack-9
UJ  10.0.1.175  15.38 KB   256          ?                 a3e7b0b7-0aa3-4fc8-af9d-f63c7b7177cd  mb-rack-9
```

**Comment by mbdcos** [comment]
```
$ cat options.json 
{
  "service": {
    "name": "cassandra-mb",
    "data_center": "mb-data-center",
    "rack": "mb-rack-9"
  }
}

# ssh to any agent running node-<instance_id>-server and run 

docker run --net=host -ti cassandra:3.0.12 nodetool status

Datacenter: mb-data-center
==========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns (effective)  Host ID                               Rack
UN  10.0.0.9    79.69 KB   256          70.0%             6c4d999c-f281-447f-8b84-60d54136eb6f  mb-rack-9
UN  10.0.1.254  101.29 KB  256          65.7%             3ad4753f-940d-44eb-9341-e9b51a58ff27  mb-rack-9
UN  10.0.1.175  83.78 KB   256          64.3%             a3e7b0b7-0aa3-4fc8-af9d-f63c7b7177cd  mb-rack-9

```

**Pull request merged**
