### PR TITLE
cli: Update kingpin vendor

### PR DESCRIPTION
**Pull request by nlsun**
This will enable the cli to use optional subcommands.

### CODE REVIEW

**Comment by nlsun** [comment]
@jsrodman 
```
[19:49:21]# github.com/mesosphere/dcos-commons/frameworks/kafka/cli/dcos-kafka
[19:49:21]./main.go:19: cannot use app (type *"gopkg.in/alecthomas/kingpin.v3-unstable".Application) as type *"github.com/mesosphere/dcos-commons/frameworks/kafka/cli/dcos-kafka/vendor/gopkg.in/alecthomas/kingpin.v3-unstable".Application in argument to handleBrokerSection
[19:49:21]./main.go:20: cannot use app (type *"gopkg.in/alecthomas/kingpin.v3-unstable".Application) as type *"github.com/mesosphere/dcos-commons/frameworks/kafka/cli/dcos-kafka/vendor/gopkg.in/alecthomas/kingpin.v3-unstable".Application in argument to handleTopicSection
[19:49:21]Process exited with code 1

```

**Comment by jsrodman** [comment]
@nlsun did this get solved in discussion with James DeFelice? I'm not much of a go expert as you may have seen :-(

**Comment by nlsun** [comment]
It seems the build failed before because the symlink I had before assumed that the root dir was called "dcos-commons", but it was actually called "build"

**Comment by nlsun** [comment]
@jsrodman AWS failures?
```
[17:36:14][Step 4/4] Failed to execute script cli
[17:36:14][Step 4/4] Traceback (most recent call last):
[17:36:14][Step 4/4]   File "dcos_launch/cli.py", line 134, in <module>
[17:36:14][Step 4/4]   File "dcos_launch/cli.py", line 126, in main
[17:36:14][Step 4/4]   File "dcos_launch/cli.py", line 92, in do_main
[17:36:14][Step 4/4]   File "dcos_launch/aws.py", line 75, in wait
[17:36:14][Step 4/4]   File "dcos_test_utils/aws.py", line 211, in wait_for_complete
[17:36:14][Step 4/4]   File "dcos_test_utils/aws.py", line 203, in wait_for_status_change
[17:36:14][Step 4/4]   File "site-packages/retrying.py", line 49, in wrapped_f
[17:36:14][Step 4/4]   File "site-packages/retrying.py", line 206, in call
[17:36:14][Step 4/4]   File "site-packages/retrying.py", line 247, in get
[17:36:14][Step 4/4]   File "site-packages/six.py", line 686, in reraise
[17:36:14][Step 4/4]   File "site-packages/retrying.py", line 200, in call
[17:36:14][Step 4/4]   File "dcos_test_utils/aws.py", line 200, in wait_loop
[17:36:14][Step 4/4] Exception: StackStatus changed unexpectedly to: CREATE_FAILED
[17:36:15][Step 4/4] Process exited with code 255
[17:36:15][Step 4/4] Process exited with code 255
[17:36:15][Step 4/4] Step Run script in Docker (Command Line) failed
```

**Comment by nlsun** [comment]
@jsrodman ready for review

**Comment by jsrodman** [comment]
I assume this is just update kingpin, make things work with it, no other change?  hard to read a 400 file commit.

**Comment by ssk2** [comment]
@nlsun looks like you actually made two changes here. In the future, might be best to separate these into two PRs. 

Is there any reason these methods need to be public?

**Comment by nlsun** [comment]
@ssk2 Yeah, we used and vendored them while they were still public. Because we need the kingpin updates now, we had to update and re-vendor and discovered that everything went private.

**Pull request merged**
