### PR TITLE
[INFINITY-2138] add config.json cni-plugin-labels sections

### PR DESCRIPTION
**Pull request by ArtRand**

### CODE REVIEW

**Comment by triclambert** [comment]
Let's move this up from the pod level.  /cc @keithchambers

**Comment by elezar** [comment]
With regards to:
> Let's move this up from the pod level. /cc @keithchambers

That's what INFINITY-1649 does, right?

**Comment by triclambert** [comment]
That is correct.

**Comment by elezar** [comment]
For the record, this is being addressed in #1412.

**Pull request closed without merging**
