### PR TITLE
Implement SchedulerFlags wrapper around scheduler env access

### PR DESCRIPTION
**Pull request by nickbp**
Replaces direct in-scheduler env access with an explicit Flags object.
    
A non-static flags object is used for two reasons:
- support easy mocking in tests
- make it painfully obvious when low-level code is reaching out into the system env

### CODE REVIEW

**Comment by benclarkwood** [comment]
@nickbp I love everything about this.

Is there anything in particular you want review of?

**Comment by benclarkwood** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Comment by mrbrowning** [comment]
@nickbp I think it's mostly outside the scope of this PR, but could this replace all of the environment setup that occurs in the individual schedulers' ServiceSpecTests? It seems like it would require that they extend `SchedulerFlags` with their own options, but then that type would probably need to be retained (instead of getting erased as just an instance of the base-level `SchedulerFlags`) to be of any use...just spitballing, but it'd be nice to unify how we approach this in both SDK and consuming code.

The need to add a `SchedulerFlags` argument to several methods in `DefaultOfferRequirementProvider` gives me a little pause, not because of this change so much as the implicit dependencies it exposes in that class, but it's something to keep in mind.

**Comment by benclarkwood** [comment]
TBF, I think one of Nick's goals is to make people pause and be, "Wait should this really be an envvar?"

Agreed on cleaning up the downstream tests as well.

**Comment by benclarkwood** [comment]
Note, I ran this locally and it seems to be failing CI due to:
```Exception in thread "main" com.mesosphere.sdk.scheduler.SchedulerFlags$FlagException: Missing required environment variable: JAVA_HOME (errtype: NOT_FOUND)
    at com.mesosphere.sdk.scheduler.SchedulerFlags$FlagException.notFound(SchedulerFlags.java:29)
    at com.mesosphere.sdk.scheduler.SchedulerFlags$FlagStore.getRequired(SchedulerFlags.java:178)
    at com.mesosphere.sdk.scheduler.SchedulerFlags$FlagStore.access$300(SchedulerFlags.java:154)
    at com.mesosphere.sdk.scheduler.SchedulerFlags.getJavaHome(SchedulerFlags.java:135)
    at com.mesosphere.sdk.specification.DefaultService.run(DefaultService.java:88)
    at com.mesosphere.sdk.helloworld.scheduler.Main.main(Main.java:21)```

**Comment by nickbp** [comment]
Some schedulers weren't specifying `JAVA_HOME`. Cleaned them up. The system works!

**Comment by nickbp** [comment]
retest this please (jenkins threw an NPE)

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@nickbp:  you should rebase on master to absorb the elastic test fix if this fails again

**Pull request merged**
