### PR TITLE
[CASSANDRA-643] Extend seed node replacement timeout

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by elezar** [comment]
Looking at the history of this test, this should not take more than 10 minutes to complete. I can integrate this timeout increase into #1369 and then close this. @gabrielhartmann what are your thoughts?

**Comment by gabrielhartmann** [comment]
@elezar:  It shouldn't take more than 15 minutes, but it does.  I've run it manually many times and all seems well.  The logs indicate that the recovery plan is proceeding.  It always takes longer on the last node than the others.

Feel free to integrate into another PR if you like, I'd be interested to see if it fails with this 20 minute timeout.

**Comment by gabrielhartmann** [comment]
Looks like trying to replace a seed node immediately after replacing a regular node causes C* to be unhappy.  I changed the test ordering.  The test environment is unrealistic with the extreme proximity of operations in time.

**Comment by gabrielhartmann** [comment]
@NimaVaziri: You should re-review

**Comment by gabrielhartmann** [comment]
Moved to #1372.

**Pull request closed without merging**
