### PR TITLE
Retry login for up to 2 minutes

### PR DESCRIPTION
**Pull request by mellenburg**
Login sporadically flakes out if attempted directly after deployment time

### CODE REVIEW

**Comment by benclarkwood** [comment]
Kafka failed due to m4.large. Kicked off.

Cassandra, I'm not sure.

Hello World, possible flapping test. Re-running.

**Comment by elezar** [comment]
Hello world failed again, and I did actually see a `TASK_FAILED` message in the logs there. Have not been able to investigate further.

**Comment by elezar** [comment]
The hello world test in `0.30.X` reads as follows:
```
    # Run task update with new discovery prefix
    marathon_config = sdk_marathon.get_config(config.PACKAGE_NAME)
    marathon_config['env']['DISCOVERY_TASK_PREFIX'] = DISCOVERY_TASK_PREFIX + '-new'
    sdk_marathon.update_app(config.PACKAGE_NAME, marathon_config)
    sdk_tasks.check_tasks_updated(config.PACKAGE_NAME, 'discovery', original_tasks)
    new_task_id = sdk_tasks.get_task_ids(config.PACKAGE_NAME, "discovery")[0]
```

in `master` we have:
```
    # Run task update with new discovery prefix
    marathon_config = sdk_marathon.get_config(config.SERVICE_NAME)
    marathon_config['env']['DISCOVERY_TASK_PREFIX'] = DISCOVERY_TASK_PREFIX + '-new'
    sdk_marathon.update_app(config.SERVICE_NAME, marathon_config)
    sdk_tasks.check_tasks_updated(config.SERVICE_NAME, 'discovery', original_tasks)
    sdk_tasks.check_running(config.SERVICE_NAME, 4)
    new_task_id = sdk_tasks.get_task_ids(config.SERVICE_NAME, "discovery")[0]
    assert task_id != new_task_id
```
(note the inclusion of `check_running()` which ensures that this task should be reachable).

**Comment by elezar** [comment]
I thought I might as well make the change for the helloworld TLS test in this PR. If there are any objections, please feel free to revert.

**Pull request merged**
