### PR TITLE
Remove detect zones stuff

### PR DESCRIPTION
**Pull request by mpereira**

### CODE REVIEW

**Comment by benclarkwood** [comment]
I expect this to not work until #1919 merges

**Comment by mpereira** [comment]
Right, this branch is to be merged onto #1919's branch.

**Comment by benclarkwood** [comment]
Ah, I c

**Comment by benclarkwood** [comment]
Please wait and merge into master after #1919 merges. Don't want to reset it part way through CI in case this is ready before 1919.

**Comment by benclarkwood** [comment]
Please wait and merge into master after #1919 merges. Don't want to reset it part way through CI in case this is ready before 1919.

**Pull request merged**
