### PR TITLE
add zookeeper authorization

### PR DESCRIPTION
**Pull request by vargup**
Added authorization for zookeeper, where user can opt for world:anyone permission or username:password authentication. On opting username:password, it will have world readable permissions too.

### CODE REVIEW

**Comment by vargup** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@mesosphere-ci: retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Pull request merged**
