### PR TITLE
Updated resource/package JSON for elastic framework

### PR DESCRIPTION
**Pull request by loren**
- Filled out Install/Uninstall notes
- Moved packageVersion to 3.0
- Specify minDcosReleaseVersion as 1.9
- Tagged most shakedown tests as "sanity" so they are exercised in CI

### CODE REVIEW

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by loren** [comment]
@mesosphere-ci retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@loren:  In order take advantage of the bumped cluster duration, this PR needs to be rebased on master.  I've overridden the default in Jenkins so I can...

@mesosphere-ci: retest this please

**Pull request merged**
