### PR TITLE
Python3 typos in publish_http.py

### PR DESCRIPTION
**Pull request by mnp**

### CODE REVIEW

**Comment by ssk2** [comment]
ok to test

**Comment by frankscholten** [comment]
Any update on this one? We are running into the python3 error.

**Comment by jsrodman** [comment]
I'll re-merge in master, and call it a day. We have no automated coverage of this file as far as I know.

**Comment by jsrodman** [comment]
You know what, I'm far more likely to make an error rebasing someone else's fork off our current master than there's any value in re-running tests that don't even exercise the file.  

Boom.

**Pull request merged**
