### PR TITLE
[INFINITY-2075] Fix DefaultSchedulerTest.testConfigurationUpdate

### PR DESCRIPTION
**Pull request by benclarkwood**
Wait for task to be starting before sending TASK_RUNNING status as that is what happens in the real world.

### CODE REVIEW

**Comment by NimaVaziri** [comment]
@benclarkwood given this only touches the SDK unit tests (which passed), should we merge or rerun the failed tests?

**Comment by benclarkwood** [comment]
@NimaVaziri I see no reason to break protocol for this. Kicked off re-runs.

**Comment by NimaVaziri** [comment]
Fair. Just reminded me of https://github.com/mesosphere/dcos-commons/pull/1286, save for the breakage.

**Comment by benclarkwood** [comment]
True. That was at peak testing frustration. I want to get a sense for where we are at now (I think we are better than we were then).

**Pull request merged**
