### PR TITLE
Fixes Offline Issues with Elasticsearch

### PR DESCRIPTION
**Pull request by ANierbeck**
Please take a in depth view on this Pull-Request. 
For us to have it working, we needed to "hard-code" the following URI for the elastic statsd plugin: 

```
STATSD_PLUGIN="http://master.mesos:8082/elastic/uris/elasticsearch-statsd-$ELASTIC_VERSION.0.zip"
```

This pullrequest is for mere Pointers on where to touch the code base to have a fully offline capable installation of elastic search. 

Please also make sure that there is an adaption in the univers module.

### CODE REVIEW

**Comment by loren** [comment]
I think this issue got addressed by https://github.com/mesosphere/dcos-commons/pull/1017

**Comment by ANierbeck** [comment]
Oh great when will it be available?

**Comment by loren** [comment]
It merged into master this morning, so it should be released in the Universe in the next two weeks

**Comment by ANierbeck** [comment]
Please also take a look at the following patch, 
there is also a JRE issue regarding this package: 
https://github.com/mesosphere/universe/pull/1197

**Comment by ANierbeck** [comment]
@loren could you please make sure that those changes are also taken into account for the BETA version?
We couldn't find the sources for the BETA packages of Elastic. That Package still contains this issue. 

Thanks, Achim

**Comment by ANierbeck** [comment]
@loren ... turned out it has been fixed in the latest 5.4.1 based version. 
Thought there is still the question, which repository does host the beta packages? Or are those packages closed?

**Pull request closed without merging**
