### PR TITLE
[INFINITY-1395] Add plan-summary endpoint

### PR DESCRIPTION
**Pull request by gabrielhartmann**
`http://gabriel-6-elasticl-1nuxgnksmygqx-1734026918.us-west-2.elb.amazonaws.com/service/hello-world/v1/plan-summary`

```
[{
		status: "COMPLETE",
		message: "com.mesosphere.sdk.scheduler.plan.DefaultPlan: 'deploy [7b225031-2e09-46a0-a7e1-61fc4dbdb16b]' has status: 'COMPLETE'.",
		name: "deploy"
	},
	{
		status: "COMPLETE",
		message: "com.mesosphere.sdk.scheduler.plan.DefaultPlan: 'recovery [2ddacb1a-8179-40f4-b531-923d5209f817]' has status: 'COMPLETE'.",
		name: "recovery"
	}
]
```

### CODE REVIEW

**Comment by keithchambers** [comment]
Another approach a query parameter of the plans endpoint.

/v1/plans?fields=status,message,name

**Comment by gabrielhartmann** [comment]
I chose this approach as it matches the `-summary` of the Mesos API.  They have `state` and `state-summary`

**Comment by mohitsoni** [comment]
TBH, @keithchambers's suggestion is valid from a general REST API design perspective. 
Although, @gabrielhartmann's implementation is more consistent with how API's are currently designed and consumed in the Mesos ecosystem.

**Comment by benclarkwood** [comment]
Well. I've showed up too late to this party to say that the order of status / message / name will hurt me every time I look at this. But it's meant for computers so meh.

**Comment by benclarkwood** [comment]
https://jira.mesosphere.com/browse/INFINITY-1398

**Comment by benclarkwood** [comment]
https://github.com/mesosphere/dcos-commons/pull/914 fixes what Nick pointed out.

**Pull request merged**
