### PR TITLE
[INFINITY-2583][INFINITY-2831] Ensure uniform security settings for Elastic

### PR DESCRIPTION
**Pull request by elezar**
This PR splits #1871 into a separate PR for Elastic.

### CODE REVIEW

**Comment by mpereira** [comment]
Should we do something similar for kibana too? https://github.com/mesosphere/dcos-commons/blob/master/frameworks/elastic/universe-kibana/config.json#L39-L43

**Comment by elezar** [comment]
@mpereira what would you propose? Simply changing the property to `elasticsearch_transport_encryption`, or some more complex expansion? @loren @benclarkwood what would make sense in this case?

**Comment by mpereira** [comment]
@elezar would the same shape make sense?
```
kibana config.json
{ "service": { "security": { "transport_encryption": { "enabled": true } } } }
```
> This is tracked separately

👍

**Comment by elezar** [comment]
I've added a comment to the Kibana JIRA.

**Pull request merged**
