### PR TITLE
Use Mesos 1.2.0-rc1 instead of SNAPSHOT

### PR DESCRIPTION
**Pull request by loren**
Fetch RC1 from Maven Central instead of SNAPSHOT from the less available repository.apache.org to make CI work more reliably.

### CODE REVIEW

**Comment by loren** [comment]
Failed with unrelated download problem: ``` > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/com/github/ksoichiro/gradle-console-reporter/0.4.0/gradle-console-reporter-0.4.0.pom'. Received status code 502 from server: Bad Gateway```

**Comment by loren** [comment]
retest this please

**Comment by loren** [comment]
Failed with ```         > Could not GET 'https://plugins.gradle.org/m2/org/codehaus/groovy/groovy-backports-compat23/2.4.4/groovy-backports-compat23-2.4.4.jar'. Received status code 502 from server: Bad Gateway
```

**Comment by loren** [comment]
retest this please

**Comment by mrbrowning** [comment]
Looks good, could you remove the `https://repository.apache.org` Maven repo from repositories in `build.gradle`?

**Comment by loren** [comment]
Yep, done.

**Pull request merged**
