### PR TITLE
INFINITY-3153 Support HTTP[S]_PROXY/NO_PROXY envvars

### PR DESCRIPTION
**Pull request by nickbp**
Use Go's `http.ProxyFromEnvironment` when performing requests to honor these envvars automatically, and align with the main DC/OS CLI's behavior.

### CODE REVIEW

**Comment by nickbp** [comment]
Verified proxy behavior by hand:

```
$ ./dcos-service-cli-linux cassandra pod list -v
HTTP Query: GET http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod
Response: 404 Not Found

$ http_proxy=localhost:9128 ./dcos-service-cli-linux cassandra pod list -v
HTTP Query: GET http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod
HTTP GET Query for http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod failed: proxyconnect tcp: dial tcp 127.0.0.1:9128: getsockopt: connection refused

$ no_proxy=dcos-cluster.us-west-2.elb.amazonaws.com http_proxy=localhost:9128 ./dcos-service-cli-linux cassandra pod list -v
HTTP Query: GET http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod
Response: 404 Not Found

$ no_proxy=.elb.amazonaws.com http_proxy=localhost:9128 ./dcos-service-cli-linux cassandra pod list -v
HTTP Query: GET http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod
Response: 404 Not Found

$ no_proxy=hey.elb.amazonaws.com http_proxy=localhost:9128 ./dcos-service-cli-linux cassandra pod list -v
HTTP Query: GET http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod
HTTP GET Query for http://dcos-cluster.us-west-2.elb.amazonaws.com/service/cassandra/v1/pod failed: proxyconnect tcp: dial tcp 127.0.0.1:9128: getsockopt: connection refused
```

**Comment by nickbp** [comment]
Looks like using the default Go timeouts actually increases our test flakiness. Going to back off and leave the Transport object as-is, just adding the proxy setting to what we were doing before.

**Comment by benclarkwood** [comment]
More generally, we could consider building a simple http test fixture we can use to test more end to end in unit tests.

In the distant future, we should also have an integration test for the CLI to test all the built-in commands (I don't think we have 100% coverage in our tests?)

**Comment by nickbp** [comment]
At the moment, test coverage is via a combination of:
- Integration tests for hello-world exercising some basic commands (e.g. `pod list`)
- Unit tests for a subset of commands (mainly `plan` and `update` commands at the moment?) -- these involve running a test HTTP server that returns a preset response from disk
Doesn't really cover proxy settings, which would probably involve pointing an SSH proxy at a real cluster and hoping that none of this turns out to be flaky

**Pull request merged**
