### PR TITLE
[INFINITY-3027] Reorder service settings

### PR DESCRIPTION
**Pull request by elezar**
This PR reorders the service settings in `config.json` for consistency across services.

I also noted that some of the `mesos_api_version` properties were not `enum`s, and I have updated this.

I implemented a quick python script to do this and included it as part of the PR.

### CODE REVIEW

**Comment by benclarkwood** [comment]
All the changes look correct to me. Nice work, @elezar.

**Comment by benclarkwood** [comment]
(I kicked the two suites that failed to get a cluster)

**Comment by nickbp** [comment]
Another cluster flake on hello-world, gave that a kick.

**Comment by benclarkwood** [comment]
Merged, as the only failing test is the known failing C* test.

**Pull request merged**
