### PR TITLE
Fix recovery step clearance of resource and persistence ids

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by nickbp** [comment]
Going to commute, will merge this and bump #745 to include it if it hasn't exploded by the time I'm home.

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by nickbp** [comment]
Cosmos/Marathon 503 error flake.

**Comment by gabrielhartmann** [comment]
retest this please

**Comment by nickbp** [comment]
might be significant, `test_permanently_replace_namenodes`

**Comment by nickbp** [comment]
looked at the scheduler logs, and it appears that the scheduler was just having trouble finding a suitable spot for the replacement node on the test cluster:
- some offers fail on: `FAIL(TaskTypeRule): Found a task matching avoided type 'journal' on this agent.`
- others fail on: `FAIL(TaskTypeRule): Found a task matching avoided type 'name' on this agent.` (and insufficient ports)
- yet others fail on insufficient ports

task layout at time of uninstall was:
```
ID							Name		State	Started		Stopped		Host
journal-0-node__38679c90-fb53-4091-88fb-68bb1ceb1cc4	journal-0-node	KILLED	39 minutes ago	12 minutes ago	10.0.2.24	Sandbox
journal-1-node__070faf13-a1cf-48d0-a1f4-df6bbe9353e8	journal-1-node	KILLED	39 minutes ago	12 minutes ago	10.0.2.153	Sandbox
data-2-node__5bd23c5f-a07e-4342-aad1-e9ee64833c91	data-2-node	KILLED	33 minutes ago	12 minutes ago	10.0.2.153	Sandbox
journal-2-node__d4ac6791-c019-4e9a-b754-92392a954476	journal-2-node	KILLED	39 minutes ago	12 minutes ago	10.0.3.146	Sandbox
data-1-node__0e30a928-f8ca-4553-8356-cf8e8f1c7354	data-1-node	KILLED	34 minutes ago	12 minutes ago	10.0.3.146	Sandbox
name-1-zkfc__2e57dd63-766f-4bff-b221-44d611a872d9	name-1-zkfc	KILLED	28 minutes ago	12 minutes ago	10.0.1.44	Sandbox
data-0-node__5772b4bb-151d-49e5-862c-388d23bd9cfc	data-0-node	KILLED	34 minutes ago	12 minutes ago	10.0.1.44	Sandbox
name-1-node__31c528d1-b823-4b7d-9965-ecd83f4caf5f	name-1-node	KILLED	28 minutes ago	12 minutes ago	10.0.1.44	Sandbox
```

**Comment by nickbp** [comment]
Filed INFINITY-1176 to revisit cleanup behavior, but in the meantime it's worth having the fix

**Pull request merged**
