### PR TITLE
[DCOS-52831] Add Grafana dashboard to C* project with README

### PR DESCRIPTION
**Pull request by viivek46**
## What changes are proposed in this PR? 

Resolves [DCOS-53276](https://jira.mesosphere.com/browse/DCOS-53276)

add the Grafana dashboard as a file inside the Cassandra project.
The idea here is that we want users to be able to deploy their Cassandra cluster (or clusters) and right after easily deploy the monitoring service so they can properly track metrics.

## How were these changes tested?
Manually testing

### CODE REVIEW

**Comment by viivek46** [comment]
> The 1.13 dashboard looks good. Please do the same w/ 1.12 and rebase this branch w/ `master`

@samvantran should we be merging it with master or keep a separate branch for dashboard/alerts , as finally we have to merge this code into grafana-dashboards repo.

**Comment by samvantran** [comment]
> should we be merging it with master or keep a separate branch for dashboard/alerts , as finally we have to merge this code into grafana-dashboards repo.

Good point @viivek46. Okay let's close this PR and create a new one to point to a branch specific to dashboards-and-alerts similar to what we did in Kafka: https://github.com/mesosphere/dcos-kafka-service/pull/418

**Comment by viivek46** [comment]
closing this PR and creating new PR pointing to "cassandra-dashboards-and-alerts" branch

**Comment by viivek46** [comment]
@samvantran  new PR : https://github.com/mesosphere/dcos-commons/pull/3075

**Pull request closed without merging**
