### PR TITLE
[DCOS-38928] Backport sdk_tasks.get_summary() from master.

### PR DESCRIPTION
**Pull request by porridge**
This makes it capable of returning more than 100 tasks.
This changed the exposed API, but I audited the usage of get_summary()
in this repo and just a couple of lines needed changing.

### CODE REVIEW

**Comment by porridge** [comment]
The answer to both of your questions is that I tried to deviate as little as possible from the code in master, so I copied both `sdk_agents.py` and the functions/constants in `sdk_tasks.py` from master in its entirety.

**Comment by porridge** [comment]
FWIW the `infinity/hello-world-19` test failure seems to be an unrelated flake. Restarted.

**Comment by porridge** [comment]
Or maybe it's not so unrelated. Improved the exception message to see what's actually going on there.

**Comment by porridge** [comment]
It looks more like sdk-0.40 is broken on 1.9 but there was no test run in that configuration for the last week, so this happens to be the first PR where the breakage surfaced.
Trying to confirm this by creating another mostly-no-op PR just to make completely sure my changes are not involved: https://github.com/mesosphere/dcos-commons/pull/2689

**Comment by elezar** [comment]
The failure here on 1.9 is pretty strange:
in `get_task_host(task_name)` we have:
```python
    host = None
    for label in task_info['labels']:
        if label['key'] == 'offer_hostname':
            host = label['value']
            break
```
clearly shows:
```json
[2018-09-27 16:20:30,799|sdk_cmd|INFO]: STDOUT:
[
  {
    "container": {
      "type": "MESOS"
    },
    "executor_id": "hello__de1b9760-4fce-4aaf-bc39-dfe17dba12e5",
    "framework_id": "cbdc42f9-b48c-4823-a86a-345ebbbe4104-0020",
    "id": "hello-0-server__901b1c16-d3d7-4a14-b392-af5c2cb70465",
    "labels": [
      {
        "key": "goal_state",
        "value": "RUNNING"
      },
      {
        "key": "index",
        "value": "0"
      },
      {
        "key": "offer_attributes",
        "value": ""
      },
      {
        "key": "offer_hostname",
        "value": "10.0.0.144"
      },
      {
        "key": "target_configuration",
        "value": "8c53e37a-a15a-48ed-abdc-0c173998d528"
      },
      {
        "key": "task_type",
        "value": "hello"
      }
    ],
    "name": "hello-0-server",
    "resources": {
      "cpus": 0.1,
      "disk": 25.0,
      "gpus": 0.0,
      "mem": 252.0
    },
    "slave_id": "cbdc42f9-b48c-4823-a86a-345ebbbe4104-S10",
    "state": "TASK_STAGING",
    "statuses": [],
    "user": "nobody"
  }
]
```
Meaning that `host` should have been set to `10.0.0.144` here.

Could it be that on other versions of DC/OS the same "failure" occurs, but the state summary has sufficient information on the task in question -- note that it's still in a `TASK_STAGING` state.

**Comment by porridge** [comment]
@elezar the problem here is not with the CLI, it shows the task we are looking for.
It seems to be a problem with the `get_summary` returning only the scheduler task, and omitting the `hello-0-server` for some reason.
I've installed a 1.9 cluster and are attempting to reproduce this.

**Comment by porridge** [comment]
Trying to run this test manually in the docker container I get flooded with:
```
[2018-09-28 14:54:03,159|dcos.http|ERROR]: HTTP Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/dcos/http.py", line 172, in _request
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 309, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 383, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/mesos/tasks': No schema supplied. Perhaps you meant http:///mesos/tasks?
```

**Comment by porridge** [comment]
Then at the end the following which has a bit more context:
```
INTERNALERROR>   File "/build/testing/sdk_diag.py", line 123, in handle_test_report
INTERNALERROR>     new_task_ids = [task.id for task in sdk_tasks.get_summary(with_completed=True)
INTERNALERROR>   File "/build/testing/sdk_tasks.py", line 138, in get_summary
INTERNALERROR>     cluster_tasks = sdk_cmd.cluster_request("GET", "/mesos/tasks").json()["tasks"]
INTERNALERROR>   File "/build/testing/sdk_cmd.py", line 116, in cluster_request
INTERNALERROR>     return retry_fn()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 49, in wrapped_f
INTERNALERROR>     return Retrying(*dargs, **dkw).call(f, *args, **kw)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 212, in call
INTERNALERROR>     raise attempt.get()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 247, in get
INTERNALERROR>     six.reraise(self.value[0], self.value[1], self.value[2])
INTERNALERROR>   File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
INTERNALERROR>     raise value
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/retrying.py", line 200, in call
INTERNALERROR>     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
INTERNALERROR>   File "/build/testing/sdk_cmd.py", line 115, in retry_fn
INTERNALERROR>     return fn()
INTERNALERROR>   File "/build/testing/sdk_cmd.py", line 82, in fn
INTERNALERROR>     response = dcos.http.request(method, url, verify=verify, **kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/dcos/http.py", line 248, in request
INTERNALERROR>     **kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/dcos/util.py", line 604, in timer
INTERNALERROR>     return fn(*args, **kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/dcos/http.py", line 189, in _request
INTERNALERROR>     raise DCOSException('HTTP Exception: {}'.format(e))
INTERNALERROR> dcos.errors.DCOSException: HTTP Exception: Invalid URL '/mesos/tasks': No schema supplied. Perhaps you meant http:///mesos/tasks?
```

**Comment by porridge** [comment]
I ran the failing test manually on the 1.9 cluster, and it passed.

**Comment by porridge** [comment]
```
[2018-09-28 16:05:13,739|sdk_plan|INFO]: Waiting for deploy plan to have COMPLETE status:
deploy COMPLETE:
- hello COMPLETE: hello-0:[server]=COMPLETE
- world COMPLETE: 
[2018-09-28 16:05:15,765|sdk_cmd|INFO]: STDOUT:
{
  "pod": "hello-0",
  "tasks": ["hello-0-server"]
}
[2018-09-28 16:05:16,248|sdk_tasks|INFO]: Waiting for tasks starting with "hello" to have updated ids:
- Old tasks (remaining): set()
- New tasks (launched): set()
[2018-09-28 16:05:17,740|sdk_tasks|INFO]: All of the tasks starting with "hello" have updated
- Old tasks: {'hello-0-server__828f63f9-479c-4b92-98a7-1e112d6ba67b'}
- New tasks: {'hello-0-server__f66ad4eb-90cb-4577-ade9-17d57c5586ab'}
[2018-09-28 16:05:19,759|sdk_cmd|INFO]: STDOUT:
[
  {
    "container": {
      "type": "MESOS"
    },
    "executor_id": "hello__1e70ec0f-31ce-4e89-8eb5-b045ace68833",
    "framework_id": "1ef096ab-1260-49e1-98af-994f012e026a-0002",
    "id": "hello-0-server__f66ad4eb-90cb-4577-ade9-17d57c5586ab",
    "labels": [
      {
        "key": "goal_state",
        "value": "RUNNING"
      },
      {
        "key": "index",
        "value": "0"
      },
      {
        "key": "offer_attributes",
        "value": ""
      },
      {
        "key": "offer_hostname",
        "value": "10.0.0.78"
      },
      {
        "key": "target_configuration",
        "value": "5d756cbf-9953-411f-aff7-b1b12d199085"
      },
      {
        "key": "task_type",
        "value": "hello"
      }
    ],
    "name": "hello-0-server",
    "resources": {
      "cpus": 0.1,
      "disk": 25.0,
      "gpus": 0.0,
      "mem": 252.0
    },
    "slave_id": "1ef096ab-1260-49e1-98af-994f012e026a-S5",
    "state": "TASK_STAGING",
    "statuses": [],
    "user": "nobody"
  }
]
[2018-09-28 16:05:20,247|sdk_cmd|INFO]: Got 200 for GET /mesos/tasks
[2018-09-28 16:05:20,726|sdk_cmd|INFO]: Got 200 for GET /mesos/slaves
[2018-09-28 16:05:20,727|sdk_tasks|INFO]: Task summary (with_completed=False, task_name=[None]):
- Task[name="hello-world"	state=TASK_RUNNING	id=hello-world.28a7cb44-c338-11e8-a13f-5edd7089964e	host=10.0.0.78	framework_id=1ef096ab-1260-49e1-98af-994f012e026a-0001	agent_id=1ef096ab-1260-49e1-98af-994f012e026a-S5]
- Task[name="hello-0-server"	state=TASK_STAGING	id=hello-0-server__f66ad4eb-90cb-4577-ade9-17d57c5586ab	host=10.0.0.78	framework_id=1ef096ab-1260-49e1-98af-994f012e026a-0002	agent_id=1ef096ab-1260-49e1-98af-994f012e026a-S5]
PASSED
```

**Comment by elezar** [comment]
It seems as if we're not properly setting the cluster URL. Hence the https:///mesos/tasks? Or am I once again missing context on my phone?

**Comment by porridge** [comment]
The cause for `https:///mesos/tasks` was that I had not done a `dcos login` inside the container. This problem is gone now. The fact that the test passed when ran locally seems to confirm that it is a race after all, I will take a closer look again today, oncall permitting.

**Comment by porridge** [comment]
Cleaning up stale PRs.

**Pull request closed without merging**
