### PR TITLE
Always update discovery info port when reserved port has changed

### PR DESCRIPTION
**Pull request by mrbrowning**

### CODE REVIEW

**Comment by mbdcos** [comment]
LGTM. Thanks @mrbrowning

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
@mrbrowning please take a look at last two commits

**Comment by mrbrowning** [comment]
👍

**Comment by mbdcos** [comment]
retest this please

**Comment by mbdcos** [comment]
retest this please

**Pull request merged**
