### PR TITLE
Reference service integration tests

### PR DESCRIPTION
**Pull request by nickbp**
Sets up the initial structure, including (disabled) tests for bumping CPU/taskcount which can be reenabled when those are fixed.

Deletes the '_example' CLI in favor of the one in the reference scheduler.

### CODE REVIEW

**Comment by nickbp** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Comment by nickbp** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
Merged with #264

**Pull request closed without merging**
