### PR TITLE
[D2IQ-63344] Upgrade Cassandra from 3.11.5 to 3.11.6

### PR DESCRIPTION
**Pull request by farhan5900**
Resolves [D2IQ-63344](https://jira.d2iq.com/browse/D2IQ-63344).

It addresses following points:
* Upgrade Cassandra version from 3.11.5 to 3.11.6
* Include configuration `max_queued_native_transport_requests`

### CODE REVIEW

**Comment by farhan5900** [comment]
Thanks @rishabh96b for the changes. If we are not using `max_queued_native_transport_requests` in `cassandra.yaml` file, we don't need `TASKCFG_ALL_` prefix in marathon file the configuration. I am removing it.

**Comment by rishabh96b** [comment]
Jenkins job for pushing the image is failing with 
```an exception which occurred:

	in field java.util.HashMap.loadFactor

	in object java.util.HashMap@62fd69b5

	in field org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.closures

	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@217b20de

	in object org.jenkinsci.plugins.workflow.cps.CpsThreadGroup@217b20de

Caused: java.lang.IllegalAccessException: Class org.jboss.marshalling.river.RiverMarshaller can not access a member of class java.util.HashMap with modifiers "final"

	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)

	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)

	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)

	at java.lang.reflect.Field.getFloat(Field.java:645)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1028)

Caused: java.io.InvalidObjectException: Unexpected illegal access exception

	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1037)

	at org.jboss.marshalling.river.RiverObjectOutputStream.defaultWriteObject(RiverObjectOutputStream.java:165)

	at java.util.HashMap.writeObject(HashMap.java:1360)

	at sun.reflect.GeneratedMethodAccessor4455.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.jboss.marshalling.reflect.JDKSpecific$SerMethods.callWriteObject(JDKSpecific.java:156)

	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:191)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:976)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)

	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)

	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)

	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)

	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.lambda$writeObject$0(RiverWriter.java:144)

	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:136)

	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.writeObject(RiverWriter.java:143)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:482)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:458)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:445)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:372)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:83)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:244)

	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:232)

	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:64)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)

	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Finished: FAILURE```

**Comment by farhan5900** [comment]
@rishabh96b The concerned tag is used for integration test only and there is not yet released tag for `3.11.6` from Cassandra. So we can keep it to `3.11.5` for now.

**Comment by farhan5900** [comment]
@viivek46 The tag is made available today only, so I will switch it back to latest tag. About the change in ubuntu version, there are some repository support removed for Ubuntu 18.10, it is better to use LTS version. Anyway I am removing that part from this PR because I have raised separate [PR#3237](https://github.com/mesosphere/dcos-commons/pull/3237) for that.

**Pull request merged**
