### PR TITLE
[INFINITY-2540] Re-enable the v1 test for strict

### PR DESCRIPTION
**Pull request by benclarkwood**

### CODE REVIEW

**Comment by benclarkwood** [comment]
Strict run: https://teamcity.mesosphere.io/viewQueued.html?itemId=835335

**Comment by elezar** [comment]
Should we enable the strict mode PR tests now?

**Comment by benclarkwood** [comment]
The v1 api test does not yet pass in strict mode. Closing this for now.

**Comment by elezar** [comment]
@benclarkwood I have created #1838 to integrate the newer version of the libmesos bundle. This branch can be deleted.

**Pull request closed without merging**
