### PR TITLE
Release Elastic 1.0.7

### PR DESCRIPTION
**Pull request by benclarkwood**
Switch naming convention to use *-node rather than *-server

### CODE REVIEW

**Comment by benclarkwood** [comment]
Susan: This + another release in a week or so will fix the elastic upgrade integration test (the upgrade being destructive was okay'd)

**Comment by susanxhuynh** [comment]
Thanks, @benclarkwood This one release should suffice for fixing the upgrade test. The upgrade test does an upgrade from the latest release to the version in HEAD of master, so it will start passing after this release.

**Comment by benclarkwood** [comment]
retest this please

**Comment by gabrielhartmann** [comment]
@benclarkwood:  I rebased on `master`.  Have you filed a JIRA for re-enabling the tests which are disabled in this PR?

**Pull request closed without merging**
