### PR TITLE
Add first draft of Stateful Service README

### PR DESCRIPTION
**Pull request by gabrielhartmann**

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@NimaVaziri:  Any comments on this?

**Comment by NimaVaziri** [comment]
As discussed previously, since the task command is not as simple as its resource specifications, it would be useful to either link to how it's constructed or at the very least mention the minimally required fields of the CommandInfo and why they're needed.

**Comment by gabrielhartmann** [comment]
@NimaVaziri:  [Comment addressed here.](https://github.com/mesosphere/dcos-commons/pull/119/files#diff-4b68ea8c4b30924e190a021d01748b8cR108)

**Comment by NimaVaziri** [comment]
nice, LGTM!

**Pull request merged**
