### PR TITLE
Update limitations.md

### PR DESCRIPTION
**Pull request by sascala**

### CODE REVIEW

**Comment by keithchambers** [comment]
This is not a limitation. This is a breaking change line item in a release note.

**Comment by benclarkwood** [comment]
@sascala, @keithchambers: What is the resolution here?

Close this, and open a Jira to make sure it becomes a release note?

**Comment by sascala** [comment]
@benclarkwood That information also appears in the release notes for SDK Kafka.

**Comment by sascala** [comment]
I can erase it here if @keithchambers thinks it shouldn't appear twice.

**Comment by gabrielhartmann** [comment]
@sascala, so this PR should just be deleting this line.

**Comment by triclambert** [comment]
@keithchambers please review the relevant release notes:  https://github.com/mesosphere/dcos-commons/releases/tag/1.1.21-0.10.1.0-beta

**Comment by mbdcos** [comment]
Also see PR #833

**Comment by benclarkwood** [comment]
retest this please

**Pull request merged**
